### ISSUE TITLE
optimization 

### ISSUE THREAD

**Issue by kaif153** [Saeid-jhn/Digital-Image-Watermarking#1]
Where in the code have you used fruitfly algorithm for optimization of the embedding factor alpha ?

**Comment by Saeid-jhn** [comment]
Fruit fly optimization algorithm has not been used. I used the optimized value of alpha without implementing the Fruit fly algorithm.

**Comment by kaif153** [comment]
can you help me out  how to use optimization algorithm eg PSO or Ant colony  in watermarking? I was trying to code but am unable to do so.

**Comment by Saeid-jhn** [comment]
I know what you're looking for. I wish I could help, but I have less knowledge in PSO and ACO concept and also so busy to allocate time.
However, I think this link provides insight implementation of the methods you're looking for provided by **Prof. Seyedali Mirjalili**:

[https://www.mathworks.com/matlabcentral/fileexchange/69027-simulation-of-particles-in-particle-swarm-optimization?s_tid=prof_contriblnk](https://www.mathworks.com/matlabcentral/fileexchange/69027-simulation-of-particles-in-particle-swarm-optimization?s_tid=prof_contriblnk)

[https://www.mathworks.com/matlabcentral/fileexchange/67429-a-simple-implementation-of-particle-swarm-optimization-pso-algorithm?s_tid=prof_contriblnk](https://www.mathworks.com/matlabcentral/fileexchange/67429-a-simple-implementation-of-particle-swarm-optimization-pso-algorithm?s_tid=prof_contriblnk)

[https://www.mathworks.com/matlabcentral/fileexchange/69028-ant-colony-optimiztion-aco?s_tid=prof_contriblnk](https://www.mathworks.com/matlabcentral/fileexchange/69028-ant-colony-optimiztion-aco?s_tid=prof_contriblnk)

[https://www.youtube.com/user/thealimirjalili](https://www.youtube.com/user/thealimirjalili)

**Comment by kaif153** [comment]
thank you for your help I did almost all excpet one thing. 
Can you please tell me in codes how to write optimization function I have written OEF but now there is some t parameter which I don't understand how to code. It will be very helpful.
pg 7 of pdf 
A. FINDING THE OPTIMAL SCALING FACTOR
 under this heading i am not understanding can you explain this. 
with my optimization function without t i am getting negative value of alpha.

**Comment by Saeid-jhn** [comment]
> Fruit fly optimization algorithm has not been used. I used the optimized value of alpha without implementing the Fruit fly algorithm.

**Comment by xiangtingkong** [comment]
> 

excuse me ,I would like to ask if you have added this friut fly optimization algorithm. I dont't know where to add it .I would like to ask you.Have you tried to add other optimization algorithms?

**Comment by Saeid-jhn** [comment]
No, I haven't. The optimized value mentioned in the paper is used. This project doesn't consider any optimization.
