### ISSUE TITLE
DWT-DCT-SVD 

### ISSUE THREAD

**Issue by KunalShivhare** [Saeid-jhn/Digital-Image-Watermarking#2]
DWT-DCT-SVD is missing can you provide?

**Comment by Saeid-jhn** [comment]
Thanks for your notification. The mentioned function is not implemented yet. It is prepared as an empty template so it can be easy to extend and contribute by everyone.

**Comment by xiangtingkong** [comment]
hello,excuse me,may i ask if you have implemented this dwt-svd-dct?

>

**Comment by Saeid-jhn** [comment]
> Thanks for your notification. The mentioned function is not implemented yet. It is prepared as an empty template so it can be easy to extend and contribute by everyone.
