### ISSUE TITLE
DWT-DCT-SVD and LWT-SVD functions are missing

### ISSUE THREAD

**Issue by kamredudhamsingh** [Saeid-jhn/Digital-Image-Watermarking#3]
These functions are missing can you provide them?

**Comment by Saeid-jhn** [comment]
Thanks for your notification. I added the algorithm: DWT-SVD. The mentioned functions are not implemented yet. It is prepared as an empty template so it can be easy to extend and contribute by everyone.

**Comment by dharma88** [comment]
Following error pops up on using DWT-SVD method,

Matrix dimensions must agree.

Error in dwt_svd (line 21)
HSw_hat = HSw + alpha.*Sw;

Error in watermark (line 9)
        [watermarked_image, extracted_watermark] = dwt_svd(cover_image,watermark_logo,alpha,attack,param);

Error in main (line 101)
    [watermarked_image, extracted_watermark] = watermark(cover_image,watermark_logoi,method,alpha,attack,param);

How to resolve this.

**Comment by dharma88** [comment]
Following error pops up on using DWT-SVD method,

Matrix dimensions must agree.

Error in dwt_svd (line 21)
HSw_hat = HSw + alpha.*Sw;

Error in watermark (line 9)
[watermarked_image, extracted_watermark] = dwt_svd(cover_image,watermark_logo,alpha,attack,param);

Error in main (line 101)
[watermarked_image, extracted_watermark] = watermark(cover_image,watermark_logoi,method,alpha,attack,param);

How to resolve this.

**Comment by xiangtingkong** [comment]
> 使用DWT-SVD方法时弹出以下错误，
> 
> 矩阵尺寸必须一致。
> 
> dwt_svd中的错误（第 21 行）HSw_hat = HSw + alpha.*Sw;
> 
> 水印错误（第 9 行）[watermarked_image， extracted_watermark] = dwt_svd（cover_image，watermark_logo，alpha，攻击，参数）;
> 
> 主错误（第 101 行）[watermarked_image， extracted_watermark] = 水印（cover_image，watermark_logoi，方法，alpha，攻击，参数）;
> 
> 如何解决这个问题。

hello,have you solved this problem.
